"""Launcher shims and PATH wiring.

The installed command is a real executable in a directory on PATH, not a shell
alias. Aliases only exist inside interactive shells, so `ssh host cx usage`,
cron jobs and scripts would all fail to find them.

The shim resolves the active version through the `current` pointer at call
time, so an update takes effect immediately without rewriting it.
"""

import os
import shutil
import sys

from .jsonio import write_text
from .term import bold, dim, info, ok, warn

BEGIN = "# >>> codex-switch >>>"
END = "# <<< codex-switch <<<"

_BEGINS = frozenset([BEGIN])
_ENDS = frozenset([END])

DEFAULT_NAME = "cx"

# Stamped into every generated launcher so setup can recognise its own output
# and clean up after a rename, without guessing from the file name.
SHIM_MARKER = "codex-switch-managed-launcher"

# Aliases written by init.sh. Stripped on install so they cannot shadow the
# shim with a path that no longer exists.
STALE_ALIASES = ("alias cx=", "alias codex-switch=", "alias codex-accounts=")

POSIX_SHIM = """\
#!/usr/bin/env sh
# {marker} - generated by `{name} setup`. Edits here are overwritten.
ROOT='{root}'
if [ ! -f "$ROOT/current" ]; then
    echo "{name}: broken install at $ROOT - re-run the installer" >&2
    exit 1
fi
VERSION=$(cat "$ROOT/current")
CODEX_SWITCH_INVOKED_AS='{name}'
export CODEX_SWITCH_INVOKED_AS
exec "$ROOT/versions/$VERSION/bin/codex-switch.sh" "$@"
"""

WINDOWS_SHIM = """\
@echo off
rem {marker} - generated by `{name} setup`. Edits here are overwritten.
setlocal
set "ROOT={root}"
if not exist "%ROOT%\\current" (
    echo {name}: broken install at %ROOT% - re-run the installer 1>&2
    exit /b 1
)
set /p VERSION=<"%ROOT%\\current"
set "PYTHONIOENCODING=utf-8"
set "CODEX_SWITCH_INVOKED_AS={name}"
"{python}" "%ROOT%\\versions\\%VERSION%\\bin\\codex-accounts.py" %*
exit /b %ERRORLEVEL%
"""

PATH_BLOCK = """\
{begin}
# Managed by codex-switch. Do not edit; run `{name} setup` to rebuild.
case ":$PATH:" in
    *":{dir}:"*) ;;
    *) PATH="{dir}:$PATH" ;;
esac
export PATH
{end}
"""


# --------------------------------------------------------------------------
# naming
# --------------------------------------------------------------------------

def installed_name() -> str:
    """What the launcher on PATH should be called.

    An explicit override wins; otherwise an install that is repairing itself
    keeps the name it was invoked under, so `cxs setup` does not silently
    rename the command back to the default.
    """
    return (os.environ.get("CODEX_SWITCH_NAME")
            or os.environ.get("CODEX_SWITCH_INVOKED_AS")
            or DEFAULT_NAME)


def command_name() -> str:
    """What to call this tool in help text and error messages.

    The shim exports the name it was invoked under, so a user who installed
    under a different name is told to run *that*, not the default.
    """
    return (os.environ.get("CODEX_SWITCH_INVOKED_AS")
            or os.environ.get("CODEX_SWITCH_NAME")
            or DEFAULT_NAME)


# --------------------------------------------------------------------------
# locations
# --------------------------------------------------------------------------

def shim_dir(root: str) -> str:
    """Where the launcher itself lives.

    On Windows the shims sit inside the install root because there is no
    conventional per-user bin directory to drop them in.
    """
    override = os.environ.get("CODEX_SWITCH_BIN")
    if override:
        return os.path.abspath(os.path.expanduser(override))
    if os.name == "nt":
        return os.path.join(root, "bin")
    return os.path.join(os.path.expanduser("~"), ".local", "bin")


def rc_files():
    """Shell rc files that should get the PATH block."""
    home = os.path.expanduser("~")
    found = []
    for name in (".bashrc", ".zshrc"):
        path = os.path.join(home, name)
        if os.path.isfile(path):
            found.append(path)
    # macOS bash reads .bash_profile for login shells and often has no .bashrc.
    if sys.platform == "darwin":
        path = os.path.join(home, ".bash_profile")
        if os.path.isfile(path):
            found.append(path)

    if not found:
        shell = os.path.basename(os.environ.get("SHELL", "") or "")
        name = ".zshrc" if shell == "zsh" else ".bashrc"
        found.append(os.path.join(home, name))
    return found


# --------------------------------------------------------------------------
# shims
# --------------------------------------------------------------------------

def _is_ours(path: str) -> bool:
    """True only for a launcher this tool generated.

    Checked by content, not by file name: deleting something a user or
    distribution put there would be unforgivable.
    """
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as fh:
            head = fh.read(400)
    except OSError:
        return False
    return SHIM_MARKER in head


def _remove_superseded(target: str, keep: str) -> None:
    """Delete launchers we generated that no longer carry the current name.

    Driven by content rather than by a list of old names, so renaming the
    command leaves nothing behind that would go on resolving to a version
    directory pruning will eventually delete.
    """
    try:
        entries = os.listdir(target)
    except OSError:
        return

    for entry in entries:
        stem = entry[:-4] if entry.endswith(".cmd") else entry
        if stem == keep:
            continue
        path = os.path.join(target, entry)
        if not os.path.isfile(path) or not _is_ours(path):
            continue
        try:
            os.remove(path)
            info(f"removed superseded launcher {dim(path)}")
        except OSError as exc:
            warn(f"could not remove {path}: {exc}")


def _path_without(directory: str) -> str:
    """$PATH with `directory` removed."""
    want = os.path.normcase(os.path.normpath(directory))
    return os.pathsep.join(
        entry for entry in os.environ.get("PATH", "").split(os.pathsep)
        if entry and os.path.normcase(os.path.normpath(entry)) != want)


def _warn_if_shadowing(target: str, name: str) -> None:
    """Point out an existing command of the same name elsewhere on PATH.

    The PATH block prepends the shim directory, so anything already called
    `cx` stops being what runs. Nothing is deleted - the other command is
    still on disk, just no longer first.

    The search deliberately excludes our own directory, or it would find the
    shim written moments ago whenever that directory is already on PATH.
    """
    existing = shutil.which(name, path=_path_without(target))
    if not existing:
        return

    warn(f"{bold(name)} already existed at {existing}")
    print(dim(f"     {target} goes first on PATH, so `{name}` now runs this "
              "tool instead"))
    print(dim(f"     that other {name} is untouched on disk - run it by full "
              "path, or"))
    print(dim("     rename this tool: re-run the installer with "
              "CODEX_SWITCH_NAME=cxs"))


def write_shims(root: str, name=None) -> str:
    """(Re)generate the launcher. Returns the directory it went into."""
    target = shim_dir(root)
    name = name or installed_name()
    os.makedirs(target, exist_ok=True)

    # Git Bash honours the shebang but will not append `.cmd`, while cmd.exe
    # and PowerShell will only run the `.cmd`. On Windows both are written side
    # by side so either shell finds a working launcher.
    posix = POSIX_SHIM.format(root=root.replace("\\", "/"), name=name,
                              marker=SHIM_MARKER)
    write_text(os.path.join(target, name), posix, executable=True)
    if os.name == "nt":
        windows = WINDOWS_SHIM.format(root=root, python=sys.executable,
                                      name=name, marker=SHIM_MARKER)
        # cmd.exe mis-parses multi-line blocks in an LF-only batch file.
        write_text(os.path.join(target, name + ".cmd"),
                   windows.replace("\n", "\r\n"))

    _remove_superseded(target, name)
    return target


# --------------------------------------------------------------------------
# PATH
# --------------------------------------------------------------------------

def _strip_managed(text: str) -> str:
    """Drop our block and any stale aliases, so re-running stays idempotent."""
    kept, inside = [], False
    for line in text.splitlines(True):
        stripped = line.strip()
        if stripped in _BEGINS:
            inside = True
            continue
        if stripped in _ENDS:
            inside = False
            continue
        if inside or stripped.startswith(STALE_ALIASES):
            continue
        kept.append(line)

    while kept and not kept[-1].strip():
        kept.pop()
    return "".join(kept)


def _ensure_path_posix(directory: str):
    block = PATH_BLOCK.format(begin=BEGIN, end=END, dir=directory,
                              name=command_name())
    touched = []
    for rc in rc_files():
        try:
            with open(rc, "r", encoding="utf-8", errors="replace") as fh:
                existing = _strip_managed(fh.read())
        except FileNotFoundError:
            existing = ""

        body = f"{existing}\n\n{block}" if existing else block
        try:
            write_text(rc, body)
        except OSError as exc:
            warn(f"could not update {rc}: {exc}")
            continue
        touched.append(rc)
    return touched


def _broadcast_env_change() -> None:
    """Tell running shells the user environment moved. Best effort."""
    try:
        import ctypes

        ctypes.windll.user32.SendMessageTimeoutW(
            0xFFFF, 0x001A, 0, ctypes.c_wchar_p("Environment"), 0, 1000, None)
    except Exception:
        pass


def _ensure_path_windows(directory: str) -> bool:
    """Prepend `directory` to the user PATH. True if it had to be added.

    Written to HKCU\\Environment rather than a PowerShell profile so cmd.exe,
    Git Bash and any GUI-launched terminal pick the command up too.
    """
    import winreg

    want = os.path.normcase(os.path.normpath(directory))
    with winreg.OpenKey(winreg.HKEY_CURRENT_USER, "Environment", 0,
                        winreg.KEY_READ | winreg.KEY_WRITE) as key:
        try:
            current, kind = winreg.QueryValueEx(key, "Path")
        except OSError:
            current, kind = "", winreg.REG_EXPAND_SZ

        entries = [p for p in str(current).split(os.pathsep) if p]
        for entry in entries:
            if os.path.normcase(os.path.normpath(entry)) == want:
                return False

        winreg.SetValueEx(key, "Path", 0, kind or winreg.REG_EXPAND_SZ,
                          os.pathsep.join([directory] + entries))

    _broadcast_env_change()
    return True


def ensure_on_path(directory: str, name=None) -> None:
    """Make `directory` resolvable in future shells, reporting what changed."""
    _warn_if_shadowing(directory, name or installed_name())

    on_path = any(
        os.path.normcase(os.path.normpath(p)) ==
        os.path.normcase(os.path.normpath(directory))
        for p in os.environ.get("PATH", "").split(os.pathsep) if p
    )

    if os.name == "nt":
        try:
            added = _ensure_path_windows(directory)
        except OSError as exc:
            warn(f"could not update your PATH: {exc}")
            warn(f"add this directory to PATH by hand: {directory}")
            return
        if added:
            ok(f"added {directory} to your PATH")
        elif on_path:
            info(f"{dim(directory)} already on PATH")
        return

    touched = _ensure_path_posix(directory)
    for rc in touched:
        ok(f"PATH configured in {rc}")
    if on_path:
        info(f"{dim(directory)} already on PATH for this shell")


def activation_hint():
    """How to make the command usable in the shell that ran the installer."""
    if os.name == "nt":
        return ["open a new terminal (PATH changes do not reach this one)"]
    return [f"source {rc}" for rc in rc_files()] + ["(or open a new terminal)"]
